<a href="https://colab.research.google.com/github/robertosgpontes/tec_prog_1/blob/main/ExerciciosNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lista de Exercícios de Numpy

Deverá ser entrege até **11/02/2023** por meio do github que foi informado por vocês no [formulário](https://forms.office.com/r/YV12vEXGYF) respondido na aula de 01/02.

A entrega pela github é parte da avaliação.

## Questão 1

Crie um array 100 com valores aleatórios e ache os valores máximo e mínimo

In [2]:
import numpy as np
vetor = np.random.randint(0, 1000, 100)
print(f'Máximo:{max(vetor)}, Mínimo: {min(vetor)}')


Máximo:975, Mínimo: 13


## Questão 2
Em Geometria Analítica, um **vetor** é uma quantidade que pode ser definida por um énuplo (uma sequência ordenada de *n* elementos) em que cada elemento representa a intensidade do vetor na direção especificada pela i-ésima componente desta sequência. 

Quando pensamos em duas dimensões, por exemplo, o vetor $R = (b,a)$ define, geometricamente, a entidade representada na figura abaixo, com componentes nos eixos x e y usuais.

<img src = "https://static.todamateria.com.br/upload/im/ag/image-721.jpg?auto_optimize=low" />

O **módulo** deste vetor, também chamado de intensidade, está geometricamente relacionado ao seu comprimento, e pode ser calculado diretamente pelas suas componentes, por meio de uma operação conhecida como **produto escalar** do vetor com ele mesmo. O módulo quadrático é expresso, desta forma, por:

$|A|^2 = \vec{A} \cdot \vec{A}$

Por outro lado, o produto escalar entre dois vetores $A = (a_{x}, a_{y})$ e $B = (b_{x}, b_{y})$ é dado por:

$\vec{A} \cdot \vec{B} = a_{x} \times b_{x} + a_{y} \times b_{y}$ (e esta definição vale para qualquer que seja a dimensão do vetor).

O módulo quadrático de um vetor é, portanto:

$|A|² = a_{x}^2 + b_{x}^2$.

Dado o exposto acima, escreva uma função que retorne o módulo de um vetor n-dimensional qualquer.

In [17]:
# def modulo(*x):
#     #vetor = list(x)
#     mod = 0
#     for i in range(len(x)):
#         mod += x[i]**2
    
#     return mod

import numpy as np
def modulo2(x):
    resultado = np.sum(x**2)
    
    return resultado

modulo2(np.array([5, 5]))

50

## Questão 3

Em uma **análise de regressão**, usualmente estamos interessados em descrever relações entre variáveis de um dado conjunto de dados por meio de uma **função** que descreva, o tanto quanto possível, estas relações.

Por exemplo, no gráfico abaixo, os pontos vermelhos relacionam as medidas das duas variáveis sendo avaliadas (nos eixos x e y); e a linha azul aproxima a relação entre elas por uma função linear.

![Normdist_regression.png](https://miro.medium.com/v2/resize:fit:786/format:webp/1*LEmBCYAttxS6uI6rEyPLMQ.png)

É possível ver que nem todos os pontos obedecem exatamente à relação ditada pela reta (isto é, há pontos que não estão exatamente "sobre a reta"; mas, sim, ligeraimente acima, ou abaixo, dela). Isto, contudo, é esperado em um modelo de regressão, por inúmeras fontes de incerteza associadas às medições.

Uma das métricas que utilizamos para avaliar a qualidade de uma regressão é o **erro quadrático médio (EQM)**, que mensura a diferença total entre cada predição da regressão ($y_{prediction}$; que no nosso caso seriam os valores de y para a reta azul) com o valor real de cada i-ésima medida ($y_{i}$; que no nosso caso seriam as coordenadas y para cada ponto vermelho do gráfico). O EQM pode ser definido como:

$EQM = \frac{1}{n}\sum_{i=1}^{n}(y_{prediction} - y_{i})^2$.

Isto posto, escreva uma função que calcule o EQM recebendo, como entrada, os vetores $y_{prediction}$ e $y_{i}$. Por exemplo, digamos que sua função se chame *calculate_eqm*, ela deve operar da seguinte forma:

In [ ]:
# dados dois arrays quaisquer de mesmo tamanho, a função deve retornar o EQM
y_prediction = np.array([1,2,3])
y_i = np.array([0,0,3])
calculate_eqm(y_prediction,y_i)

1.6666666666666665

In [9]:
# Solução
def calculate_eqm(x,y):
    eqm = 0
    for i in range(len(x)):
        eqm += (x[i] - y[i])**2
    eqm = eqm/len(x)
    return eqm

y_prediction = np.array([1,2,3])
y_i = np.array([0,0,3])
calculate_eqm(y_prediction,y_i)

1.6666666666666667

## Questão 4

Crie um array 2D (bidimensional) com 1 na borda e 0 dentro

In [18]:
import numpy as np

def borda_0(n):
    arr = np.zeros((n,n), dtype=int)
    arr[0, :] = 1
    arr[n-1, :] = 1
    arr[:, 0] = 1
    arr[:, n-1] = 1
    return arr

n = 5
result = borda_0(n)
print(result)


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


## Questão 5

Como adicionar uma borda de 0's ao redor de um array 2D (bidimensional) existente

In [31]:
import numpy as np


arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.pad(arr, 1, mode='constant', constant_values=0)

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 0],
       [0, 4, 5, 6, 0],
       [0, 7, 8, 9, 0],
       [0, 0, 0, 0, 0]])

## Questão 6

 A eletroencefalografia (EEG) é uma técnica que mensura potenciais elétricos cerebrais em diversas regiões do escalpo do paciente. Suponha que você recebeu um conjunto de dados na forma de uma matriz de 64 x 512 elementos, em que cada linha contém o sinal gravado em um dos **eletrodos** espalhados pelo escalpo em um exame de EEG, e cada coluna contém um valor de potencial elétrico, em microvolts. 

Como o sinal de EEG é muito suscetível a ruídos externos (interferências na qualidade do sinal), uma operação comum para atenuar a interferência no sinal consiste em tirar a média do potencial elétrico de todos os eletrodos, e subtrair este valor de cada um deles. Isto atenua fontes de ruído ao sinal comuns a todos os eletrodos. Em termos matemáticos, o sinal processado por esta operação, $X_{e,i}$ para cada eletrodo (e) e amostra (i), é dado por:

$X_{e,i} = \hat{X_{e,i}} - \frac{1}{N}\sum_{e=1}^{N}\hat{X_{e,i}}$,

em que $\hat{X_{e,i}}$ representa o sinal original (ou seja, é a matriz de entrada de 64 x 512 elementos), e $N$ indica o total de eletrodos.

Com o exposto acima, escreva uma função que retorne uma matriz com os sinais de EEG processados conforme a operação mencionada. Sua função deve operar conforme o exemplo abaixo.

In [ ]:
# vamos supor uma matriz de entrada gerada por dados aleatórios
X = np.random.randn(64,512)
X.shape # apenas para verificar as dimensões

(64, 512)

In [ ]:
# a função deve executar a operação equacionada anteriormente, retornando uma nova matriz
X_processado = process_EEG_signal(X)
X_processado.shape

(64, 512)

In [ ]:
# Somando as diferenças entre cada elemento das duas matrizes, apenas para ilustrar que elas não são iguais
(X_processado - X).sum()

-53.08727366483029

In [ ]:
# Visualizando as matrizes, para verificar uma vez mais que, de fato, os elementos são diferentes
X

array([[ 0.29305925,  0.89663038, -0.61032202, ..., -0.88086364,
        -0.8818789 ,  0.51260497],
       [-0.01274415,  1.05439522,  0.47958092, ..., -2.15387924,
         0.70721168,  0.97029889],
       [ 1.09478371, -0.16120847,  1.58400361, ...,  0.20981813,
         2.17373837,  0.94032162],
       ...,
       [-0.45294842, -2.28939505,  1.10111998, ...,  1.63581703,
        -0.39394924, -1.13400723],
       [-0.22669886,  0.25413429, -1.17870637, ..., -0.09509442,
         0.90733806,  0.37999411],
       [ 0.15476933, -0.03654717, -1.09982762, ...,  0.67600047,
        -0.84533328, -0.56433144]])

In [ ]:
# Matriz após o processamento descrito no enunciado
X_processado

array([[ 0.36713022,  0.85772513, -0.54902169, ..., -0.85626087,
        -0.97611435,  0.51718998],
       [ 0.06132682,  1.01548997,  0.54088126, ..., -2.12927647,
         0.61297623,  0.97488389],
       [ 1.16885469, -0.20011372,  1.64530394, ...,  0.23442091,
         2.07950292,  0.94490663],
       ...,
       [-0.37887744, -2.3283003 ,  1.16242031, ...,  1.6604198 ,
        -0.4881847 , -1.12942223],
       [-0.15262788,  0.21522904, -1.11740604, ..., -0.07049164,
         0.81310261,  0.38457911],
       [ 0.22884031, -0.07545242, -1.03852729, ...,  0.70060324,
        -0.93956874, -0.55974643]])

In [5]:
# Solução
import numpy as np
Xzin = np.random.randn(64,512)


def process_eeg_signal(eeg_signal):
    N = len(eeg_signal)
    Xe = eeg_signal * (1/N)
    Xee = eeg_signal - Xe
    #for i in range(N):
     #   for j in range(len(eeg_signal[1])):
      #      Xee[i][j] = (1/N) * Xee[i][j]
    return Xee

Sinal = process_eeg_signal(Xzin)
(Sinal - Xzin).sum()


-1.3438338098653282

## Questão 7

Em estatística, um **outlier** é um valor que destoa consideravelmente da distribuição à qual está associado. Um dos critérios para idenficar outliers consiste em encontrar a **distância interquantil** (IQR), ou seja, a diferença entre o terceiro (Q3) e o primeiro quartis (Q1) da distribuição, e tomar como outliers todos os pontos abaixo de 1.5*IQR - Q1, ou acima de 1.5*IQR + Q3.

<img src = "https://blog.curso-r.com/images/posts/banner/outlier.webp" />

Escreva uma função que, dada uma matriz de dados de entrada de dimensões $N_{observações} \times N_{features}$ retorne três requisitos: 
- uma matriz booleana indicando a existência de outliers nos dados de entrada;
- a quantidade de outliers
- quem são os outliers (os valores).

**Algumas definições:**
- um *quantil* divide a distribuição, após ordenados os pontos, segundo algum ponto de corte;
- o **primeiro quartil** é o ponto para o qual 25 % dos valores da distribuição estão abaixo dele;
- o **terceiro quartil** é o ponto para o qual 75 % dos valores da distribuição estão abaixo dele.

Pode ser útil consultar a função **numpy.quantile**.

Exemplo de operação da função:

In [119]:
# Geremos um conjunto de dados qualquer
X = np.random.randn(300,15)
X

array([[ 0.72571563,  0.81702587, -0.6484116 , ..., -0.89313989,
        -1.01809252,  0.27858618],
       [-0.37251652, -0.67494245, -0.26863366, ..., -0.74820235,
        -0.18657976,  0.02707273],
       [ 0.56088444,  1.23570026, -0.63029902, ..., -0.31440872,
         0.19980021,  0.93712112],
       ...,
       [-1.1196358 , -0.96531029,  0.293035  , ...,  0.2271847 ,
        -0.34811191,  0.065243  ],
       [ 0.7694583 ,  0.88185416, -0.78702852, ..., -0.06232708,
        -0.8483832 ,  2.06401353],
       [-0.33249131, -0.52473658,  0.53928003, ..., -0.56985914,
         0.31626152, -0.20881932]])

In [ ]:
# identificamos os requisitos com nossa com nossa função "locate_outliers"
is_outlier, outliers_count, outliers = locate_outliers(X)

In [ ]:
is_outlier

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [ ]:
outliers_count

44

In [ ]:
outliers

array([-2.67240384,  3.00270904,  3.62317101,  3.18867865,  2.55581522,
       -2.82091429,  2.8757892 ,  2.70666036,  3.19514999, -3.40550318,
       -3.39825827,  2.6727295 ,  2.54498296, -2.69447104,  3.19521603,
        2.66372172, -2.77444948,  2.77421152,  2.69992869, -2.84831109,
       -2.83695779, -2.45908227,  3.07802106,  2.89314015, -2.68574682,
       -2.85019494,  2.43399574,  2.44291266, -2.92595937, -2.95911074,
       -3.03966003,  2.77543068, -2.67368414, -2.79965402, -3.0501958 ,
       -2.5437387 ,  3.08550649, -3.17666255, -3.05795476, -3.09826467,
        3.1399469 ,  3.18141942,  2.90564257, -2.89505054])

In [255]:
# Solução


import numpy as np
def outlier(Matriz):
    matriz_bool = np.zeros((Matriz.shape[0], Matriz.shape[1]), dtype=bool)
    outlier = []
    for i in range(Matriz.shape[1]):
        coluna = Matriz[:,i]
        Q1 = np.quantile(coluna, 0.25)
        Q3 = np.quantile(coluna, 0.75)
        IQR = Q3 - Q1
        superior = Q1 - 1.5 * IQR
        inferior = Q3 + 1.5 * IQR
        outlier_coluna = np.logical_or(coluna < superior, coluna > inferior)
        matriz_bool[:,i] = outlier_coluna
        outlier.extend(coluna[outlier_coluna])
    return matriz_bool, len(outlier), outlier

outlier(np.random.randn(300,300))


(array([[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]]),
 693,
 [-2.709801940092957,
  2.840279098082857,
  -3.274154502264042,
  3.286642066083947,
  -3.0007125044396443,
  2.67294794912082,
  2.7787950572316342,
  2.5773880966233937,
  2.5690792605312684,
  2.595098389982278,
  3.590715780797554,
  3.2435761833719874,
  3.649215650130772,
  -3.290741151973439,
  3.1310875433330185,
  3.3731412217701164,
  3.3293739583186883,
  3.2981578181653104,
  -2.839083762074318,
  2.73736731849187,
  2.699410609864134,
  2.743709141682415,
  -3.1242134160046917,
  -2.9348676288256246,
  2.860755401849888,
  2.874813464023245,
  -3.620962043298789,
  3.0708921140846637,
  -2.8229241669829954,
  -3.206

## Questão 8

Crie um vetor com valores que vão de 1 até 21 de dois em dois, a partir da função arange

In [257]:
vetor_2 = np.arange(1, 22, 2)
print(vetor_2)

[ 1  3  5  7  9 11 13 15 17 19 21]


## Questão 9

Crie um array de 10 com valores aleatórios

In [269]:
import numpy as np

array = np.random.randint(1, 100, 10)
print(array)


[66 30 25 30 40  9 44 78 35 92]


## Questão 10

Em estatística, a normalização de uma distribuição de dados pode ser feita subtraindo o valor médio da distribuição de cada valor do conjunto de dados, dividindo o resultado pelo desvio-padrão da distribuição. Escreva uma função que normalize os dados recebidos por um array numpy qualquer, conforme descrito anteriormente.

In [270]:
import numpy as np

def normalizar(dados):
    media = np.mean(dados)
    desvio_padrao = np.std(dados)
    dados_normalizados = (dados - media) / desvio_padrao
    return dados_normalizados

normalizar(array)

array([ 0.86062252, -0.60773817, -0.81167716, -0.60773817, -0.19986021,
       -1.46428191, -0.03670902,  1.35007608, -0.40379919,  1.92110524])

## Questão 11

Escreva uma função em numpy que receba um array contendo notas de uma turma de 100 estudantes. Considere que a nota de aprovação da turma é 5.0. A função deve retornar, em um array numpy, nesta ordem:
- a média e o desvio-padrão das notas da turma;
- o número de notas maiores que 7.0;
- o número de reprovações da turma;
- a menor nota da turma;
- a maior nota da turma.

In [316]:
import numpy as np

array = np.random.randint(0, 11, 100)


def notas_turma(x):
    media = np.mean(x)
    desvio_padrao = np.std(x)
    notas_altas, reprovado = 0, 0
    for i in range(len(x)):
        if x[i] > 7:
            notas_altas += 1
        elif x[i] < 5:
            reprovado += 1
    maior_nota = max(x)
    menor_nota = min(x)
    resultado = np.array([media, desvio_padrao, notas_altas, reprovado, maior_nota, menor_nota])
    return resultado

notas_turma(array)

array([ 4.78     ,  3.2267011, 29.       , 49.       , 10.       ,
        0.       ])